version: "3"

services:
  frontend:
    command: "npm run serve"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/usr/src/app/src
    stdin_open: true
    tty: true
  database:
    ports:
      - "27017:27017"
  backend:
    command: npm run dev
    volumes:
      - ./backend/src:/usr/src/app/src
  mailer:
    command: npm run dev
    volumes:
      - ./mailer/src:/usr/src/app/src
