version: "3"

services:
  backend:
    container_name: codestart-backend
    build: ./backend
    command: npm run dev
    environment:
      - PORT=3000
      - MAILER_URL=http://mailer:3003
      - MONGO_URL=mongodb://database:27017
      - SECRET=secret_key
      - DOMAIN=http://localhost:8080
    depends_on:
      - database
    networks:
      - codestart-network
    restart: unless-stopped
  lessons:
    container_name: codestart-lessons
    build: ./lessons
    command: npm run start
    networks:
      - codestart-network
    restart: unless-stopped
  mailer:
    container_name: codestart-mailer
    build: ./mailer
    command: npm run start
    networks:
      - codestart-network
    environment:
      - PORT=3003
      - HOST=smtp.gmail.com
      - LOGIN=your_mail_login(without @gmail.com)
      - PASSWORD=your_mail_password
    restart: unless-stopped
  database:
    container_name: codestart-database
    image: mongo:latest
    volumes:
      - database:/data/db
    networks:
      - codestart-network
    restart: unless-stopped
  frontend:
    container_name: codestart-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: serve -s dist -l 8080
    networks:
      - codestart-network
    restart: unless-stopped
  nginx:
    container_name: codestart-nginx
    build: ./nginx
    depends_on:
      - frontend
      - backend
    environment:
      - HOST=localhost
      - PORT=8080
    networks:
      - codestart-network
    ports:
      - "8080:8080"
    restart: unless-stopped
volumes:
  database:

networks:
  codestart-network:
    driver: bridge
